### ISSUE TITLE
[ 📌 Feature ] Table 컴포넌트 만들기

### ISSUE THREAD

**Issue by 909back** [909back/devlog#10]
### 👉 Description
`.mdx` 파일에서 마크다운으로 테이블이 생성되지 않아 커스텀 컴포넌트 만들기

### ✔️ Todo List
- [ ] 테이블 컴포넌트 생성
- [ ] contentlayer에서 어떻게 테이블이 렌더링 되는지 확인
- [ ] 테이블 컴포넌트 테스트
